baseURL = 'https://kfejes.github.io/'
locale = 'en-us'
title = 'Saját Agóra'
theme = "hugo-bearcub"

# Szép és tiszta URL-ek a posztokhoz (pl. domain.hu/a-cikk-cime/)
[permalinks]
  posts = '/:slug/'

# A Bear Cub téma specifikus beállításai
[params]

  description = 'Gondolatok technológiáról, permacomputingról és a független webről.'
  favicon = 'favicon.ico'

  [params.author]
    email = 'karoly.fejes@gmail.com'


# Fejléc menüpontok
[[menu.main]]
  name = 'Posztok'
  url = '/posts/'
  weight = 1

[[menu.main]]
  name = 'Rólam'
  url = '/about/'
  weight = 2
